apiVersion: v1
kind: Service
metadata:
  name: campus-connect-backend-service
  namespace: "2401137"
spec:
  type: ClusterIP
  selector:
    app: campus-connect-backend
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: campus-connect-frontend-service
  namespace: "2401137"
spec:
  type: NodePort
  selector:
    app: campus-connect-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
